# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizeduser',
            name='email',
            field=models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='EMAIL'),
        ),
    ]
